from __future__ import annotations
import hashlib
import os
from pathlib import Path

import common.log as logging
from common.yaml import yaml

from .config import GENERATED_PATH, PROJECT_CONFIG_PATH

log = logging.initialize()

EPOCH = 946684800
WINDOW = 315360000


class Preprocessor:

  def __init__(self, make):
    self.make = make
    self.root = getattr(make, "root", Path("."))
    self.config_path = self.root / PROJECT_CONFIG_PATH
    self.header_path = self.root / GENERATED_PATH / "generated" / "preprocessor.hpp"

  def generate(self) -> Path:
    if not self.config_path.exists():
      log.info(f"Preprocessor config not found: {self.config_path}")
      return self.header_path

    stale = self.root / "include"
    if stale.exists():
      log.warning(
        f"Leftover vendored headers at {stale} — the directory is retired "
        f"(headers resolve from submodules/); delete it")

    data = self._configuration()

    self.header_path.parent.mkdir(parents=True, exist_ok=True)

    catalog: list[str] = []
    groups: dict[str, list[str]] = {}
    for mapping, render in (("tokens", self._token), ("directives", self._directive)):
      for name, value in (data.get(mapping) or {}).items():
        if isinstance(value, dict):
          lines = [render(entry, each) for entry, each in value.items()]
          groups.setdefault(name, []).extend(lines)
          catalog.extend(lines)
        else:
          catalog.append(render(name, value))

    for group, lines in groups.items():
      self._write(self.header_path.parent / f"{group}.hpp", lines)
    self._write(
      self.header_path.parent / "compatibility.hpp",
      self._compatibilities(data))
    self._write(self.header_path, catalog)
    return self.header_path

  def _configuration(self) -> dict:
    resolve = getattr(self.make, "project", None)
    if resolve is not None:
      return resolve() or {}
    with open(self.config_path, "r", encoding="utf-8") as file:
      return yaml.safe_load(file) or {}

  @staticmethod
  def _compatibilities(data: dict) -> list[str]:
    rows: list[str] = []
    table = (data.get("manifest") or {}).get("compatibility") or {}
    for setting, values in table.items():
      for value, rule in (values or {}).items():
        admits = (rule or {}).get("admits") or {}
        refuses = (rule or {}).get("refuses") or {}
        for key in sorted(set(admits) | set(refuses)):
          admitted = ", ".join(admits.get(key) or [])
          refused = ", ".join(refuses.get(key) or [])
          rows.append(
            f'  {{"{setting}", "{value}", "{key}",'
            f' "{admitted}", "{refused}"}}, \\')
    if not rows:
      return ["#define SR_COMPATIBILITIES"]
    return ["#define SR_COMPATIBILITIES \\"] + rows[:-1] + [
      rows[-1].rstrip(" \\")]

  @staticmethod
  def _token(name: str, value) -> str:
    if isinstance(value, list):
      mask = " | ".join(f"(1 << {member})" for member in value)
      return f"#define {name} {value[0]}\n#define {name}_SET ({mask})"
    return f"#define {name} {value}"

  @staticmethod
  def _directive(name: str, value) -> str:
    if isinstance(value, bool):
      return f"#define {name} 1" if value else f"/* {name} disabled (false) */"
    if isinstance(value, (int, float)):
      return f"#define {name} {value}"
    text = str(value)
    if not (text.startswith('"') or text.startswith("'")):
      text = '"' + text + '"'
    return f"#define {name} {text}"

  def _write(self, path: Path, lines: list[str]) -> None:
    head = ["#pragma once", "// Generated by dev/make/preprocessor.py", ""]
    content = "\n".join(head + lines) + "\n"
    try:
      if path.read_text(encoding="utf-8") == content:
        log.debug(f"Preprocessor header unchanged: {path}")
        return
    except OSError:
      pass
    with open(path, "w", encoding="utf-8") as header:
      header.write(content)
    os.utime(path, (self._stamp(content), self._stamp(content)))
    log.info(f"Wrote preprocessor header: {path}")

  @staticmethod
  def _stamp(content: str) -> int:
    digest = hashlib.sha256(content.encode("utf-8")).digest()
    return EPOCH + int.from_bytes(digest[:4], "big") % WINDOW
